apiVersion: v1
kind: Secret
metadata:
  namespace: trading-bot-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: trading-bot-prod
  annotations:
    kubernetes.io/restrict-access: "true"
    kubernetes.io/allowed-pods: "backend-*"
    secret.kubernetes.io/rotation-period: "168h"
    secret.kubernetes.io/audit-log-enabled: "true"
    secret.kubernetes.io/last-rotated: "timestamp"
type: Opaque
data:
  POSTGRES_USER: base64_encoded_value
  POSTGRES_PASSWORD: base64_encoded_value
  TIMESCALE_USER: base64_encoded_value
  TIMESCALE_PASSWORD: base64_encoded_value
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: trading-bot-prod
  annotations:
    kubernetes.io/restrict-access: "true"
    kubernetes.io/allowed-pods: "backend-*,cache-*"
    secret.kubernetes.io/rotation-period: "168h"
    secret.kubernetes.io/audit-log-enabled: "true"
    secret.kubernetes.io/network-policy: "restricted"
type: Opaque
data:
  REDIS_PASSWORD: base64_encoded_value
  REDIS_AUTH_TOKEN: base64_encoded_value
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: trading-bot-prod
  annotations:
    kubernetes.io/restrict-access: "true"
    kubernetes.io/allowed-pods: "backend-*"
    secret.kubernetes.io/rotation-period: "720h"
    secret.kubernetes.io/audit-log-enabled: "true"
    secret.kubernetes.io/access-control: "strict"
type: Opaque
data:
  JUPITER_API_KEY: base64_encoded_value
  PUMP_FUN_API_KEY: base64_encoded_value
  DRIFT_API_KEY: base64_encoded_value
  JITO_API_KEY: base64_encoded_value
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: trading-bot-prod
  annotations:
    kubernetes.io/restrict-access: "true"
    kubernetes.io/allowed-pods: "backend-*,web-*"
    secret.kubernetes.io/rotation-period: "168h"
    secret.kubernetes.io/audit-log-enabled: "true"
    secret.kubernetes.io/key-type: "signing"
type: Opaque
data:
  JWT_SECRET_KEY: base64_encoded_value
  JWT_REFRESH_KEY: base64_encoded_value
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: trading-bot-prod
  annotations:
    kubernetes.io/restrict-access: "true"
    kubernetes.io/allowed-pods: "backend-*,web-*"
    cert-manager.io/renewal-enabled: "true"
    cert-manager.io/renewal-window: "720h"
    secret.kubernetes.io/audit-log-enabled: "true"
type: kubernetes.io/tls
data:
  tls.crt: base64_encoded_value
  tls.key: base64_encoded_value