# Kubernetes version: 1.25+
# AWS EBS CSI Driver version: 1.0+

# High-performance storage class for database persistent volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iopsPerGB: "3000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: aws/ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - ap-southeast-1a
          - ap-southeast-1b
---
# Performance-optimized storage class for Redis caching
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iopsPerGB: "3000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: aws/ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - ap-southeast-1a
          - ap-southeast-1b
---
# Storage class for monitoring and logging systems
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: monitoring-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iopsPerGB: "3000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: aws/ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - ap-southeast-1a
          - ap-southeast-1b